# Generated by Django 4.1.7 on 2023-03-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='eventposters')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('college', models.CharField(blank=True, max_length=256, null=True)),
                ('event_name', models.CharField(blank=True, max_length=256, null=True)),
                ('year_of_study', models.PositiveIntegerField(blank=True, null=True)),
                ('team_count', models.PositiveIntegerField(blank=True, null=True)),
                ('head_name', models.CharField(blank=True, max_length=256, null=True)),
                ('member_1', models.CharField(blank=True, max_length=256, null=True)),
                ('member_2', models.CharField(blank=True, max_length=256, null=True)),
                ('member_3', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsors')),
            ],
        ),
    ]
