# Generated by Django 4.1.7 on 2023-03-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fifaregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifaregistration',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to='fifa/'),
        ),
    ]
