# Generated by Django 4.1.7 on 2023-03-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_fifaregistration_payment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=256, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=256, null=True)),
                ('lead_ph_no', models.CharField(blank=True, max_length=256, null=True)),
                ('mem2', models.CharField(blank=True, max_length=256, null=True)),
                ('mem3', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('payment', models.ImageField(blank=True, null=True, upload_to='cod/')),
                ('college_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
